### ISSUE TITLE
dataset or data-set or 'data set'

### ISSUE THREAD

**Issue by psteinb** [florian-huber/weather_prediction_dataset#12]
This question drives me nuts when proof reading. Which one do we settle on? Or did we already settle on it?

**Comment by colinsauze** [comment]
I'm never sure which one to use either. Personally I tend to use dataset more, but I think that using computers since the time when we couldn't have spaces in filenames has caused me to tend to avoid spaces between words. I think data set is more traditional English, but both seem to be in common use.  Wikipedia says "data set (or dataset)". Either way the most important thing is consistency.

**Comment by psteinb** [comment]
thoughts @dafnevk or @florian-huber ?

**Comment by florian-huber** [comment]
I also prefer `dataset` over `data set`, so I suggest we keep it as it is now. 
(unless someone has strong feelings about this...)

**Comment by dafnevk** [comment]
I agree with using `dataset`, it is a common spelling and feels natural. Maybe we can leave this issue open to have a final check on consistency before the paper is submitted.

**Comment by geek-yang** [comment]
I have the same question in one of my previous papers. One reviewer strongly suggests that using `dataset` for a single form and `data sets` for the plural form. Don't know if this is standard English, but at least that reviewer let me pass after revision.

**Comment by florian-huber** [comment]
OK, thanks! So maybe we can leave it as it is and wait for the reviewer comments.
